name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  notifier_plugin:
    path: ..
  flutter_webview_plugin: ^0.3.11
  shared_preferences: ^0.5.12
  flutter_colorpicker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true