name: notifier_plugin
description: A Flutter package that makes state management easier and more efficient than it could have ever been!
version: 0.0.3
repository: https://github.com/thehumankid/notifier_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: